#!/bin/bash
# Conseguir una tabla de firewall vacía:
iptables -F
iptables -X

# Primero, prohibir toda la entrada y el forwarding:
iptables -P INPUT DROP
iptables -P FORWARD DROP

# Pero permitir toda la salida (solo para las prácticas, en un entorno real no):
iptables -P OUTPUT ACCEPT


# Routing
iptables -t nat -A POSTROUTING ! -d 192.168.0.0/16 -o eth0 -j MASQUERADE


# Permitir tráfico interfaz local
iptables -A INPUT -i lo -j ACCEPT

# Permitir todo el tráfico ICMP
iptables -A FORWARD -p icmp -j ACCEPT
iptables -A INPUT -p icmp -j ACCEPT

# Permitir conexión a internet a los móviles por wifi
iptables -A FORWARD -d 192.168.31.128/25 -j ACCEPT
iptables -A FORWARD -s 192.168.31.128/25 -j ACCEPT

# Permitir tráfico entrante en el router si son conexiones TCP ya establecidas
iptables -A INPUT -p tcp -m state --state ESTABLISHED -j ACCEPT

# Perimitir tráfico entrante a los servidores de conexiones ya establecidas
iptables -A FORWARD -p tcp -d 192.168.31.100 -s 0/0 -m state --state ESTABLISHED -j ACCEPT
iptables -A FORWARD -p tcp -d 192.168.32.100 -s 0/0 -m state --state ESTABLISHED -j ACCEPT

# Permitir DNS
iptables -A FORWARD -p udp -s 8.8.8.8 -d 0/0 --sport 53 --dport 513:65535 -j ACCEPT
iptables -A FORWARD -p udp -s 0/0 -d 8.8.8.8 --sport 513:65535 --dport 53 -j ACCEPT
iptables -A INPUT -p udp -s 8.8.8.8 -d 0/0 --sport 53 --dport 513:65535 -j ACCEPT

iptables -A FORWARD -p udp -s 8.8.4.4 -d 0/0 --sport 53 --dport 513:65535 -j ACCEPT
iptables -A FORWARD -p udp -s 0/0 -d 8.8.4.4 --sport 513:65535 --dport 53 -j ACCEPT
iptables -A INPUT -p udp -s 8.8.4.4 -d 0/0 --sport 53 --dport 513:65535 -j ACCEPT

iptables -A FORWARD -p udp -s 155.54.1.1 -d 0/0 --sport 53 --dport 513:65535 -j ACCEPT
iptables -A FORWARD -p udp -s 0/0 -d 155.54.1.1 --sport 513:65535 --dport 53 -j ACCEPT
iptables -A INPUT -p udp -s 155.54.1.1 -d 0/0 --sport 53 --dport 513:65535 -j ACCEPT

# Permitir SSH en los servidores
iptables -A FORWARD -p tcp -s 0/0 -d 192.168.31.100 --sport 513:65535 --dport 22 -m state --state NEW,ESTABLISHED -j ACCEPT
iptables -A FORWARD -p tcp -s 0/0 -d 192.168.32.100 --sport 513:65535 --dport 22 -m state --state NEW,ESTABLISHED -j ACCEPT

# Permitir SSH en el router si las conexiones van desde las organizaciones
iptables -A INPUT -p tcp -s 192.168.31.0/24 -d 192.168.31.1 --sport 513:65535 --dport 22 -m state --state NEW,ESTABLISHED -j ACCEPT
iptables -A OUTPUT -p tcp -s 192.168.31.1 -d 192.168.31.0/24 --sport 22 --dport 513:65535 -m state --state ESTABLISHED -j ACCEPT

iptables -A INPUT -p tcp -s 192.168.32.0/24 -d 192.168.32.1 --sport 513:65535 --dport 22 -m state --state NEW,ESTABLISHED -j ACCEPT
iptables -A OUTPUT -p tcp -s 192.168.32.1 -d 192.168.32.0/24 --sport 22 --dport 513:65535 -m state --state ESTABLISHED -j ACCEPT

# Permitir acceso público a los servicios web en los puertos 80, 8000, 8080 y 443:

iptables -A FORWARD -p tcp -s 0/0 -d 192.168.31.100 --sport 513:65535 --dport 80 -m state --state NEW,ESTABLISHED -j ACCEPT
iptables -A FORWARD -p tcp -s 0/0 -d 192.168.31.100 --sport 513:65535 --dport 8000 -m state --state NEW,ESTABLISHED -j ACCEPT
iptables -A FORWARD -p tcp -s 0/0 -d 192.168.31.100 --sport 513:65535 --dport 8080 -m state --state NEW,ESTABLISHED -j ACCEPT
iptables -A FORWARD -p tcp -s 0/0 -d 192.168.31.100 --sport 513:65535 --dport 443 -m state --state NEW,ESTABLISHED -j ACCEPT

# Permitir el tráfico ASTERIX entre los troncales (SIP)

iptables -A FORWARD -p udp -s 0/0 -d 192.168.31.100 --sport 513:65535 --dport 5060 -j ACCEPT
iptables -A FORWARD -p udp -s 0/0 -d 192.168.32.100 --sport 513:65535 --dport 5060 -j ACCEPT

iptables -A FORWARD -p udp -s 192.168.31.100 -d 0/0 --sport 5060 --dport 513:65535 -j ACCEPT
iptables -A FORWARD -p udp -s 192.168.32.100 -d 0/0 --sport 5060 --dport 513:65535 -j ACCEPT

# (RTP)
iptables -A FORWARD -p udp -s 0/0 -d 192.168.31.100 --sport 513:65535 --dport 10000:20000 -j ACCEPT
iptables -A FORWARD -p udp -s 0/0 -d 192.168.32.100 --sport 513:65535 --dport 10000:20000 -j ACCEPT

iptables -A FORWARD -p udp -s 192.168.31.100 -d 0/0 --sport 10000:20000 --dport 513:65535 -j ACCEPT
iptables -A FORWARD -p udp -s 192.168.32.100 -d 0/0 --sport 10000:20000 --dport 513:65535 -j ACCEPT

# Permitir SNMP entre el router y la ORG31
iptables -A INPUT -p udp -s 192.168.31.100 -d 192.168.31.1 --dport 161 -j ACCEPT

# Permitir SNMP entre el router y la ORG32
iptables -A INPUT -p udp -s 192.168.32.100 -d 192.168.32.1 --dport 161 -j ACCEPT
