#!/bin/bash

if [ "$EUID" -ne "0" ]; then
  echo "Ejecuta como root (sudo)."
  exit
fi

USO="Uso: \#$0 router|server1|server2"

if [ "$#" -lt "1" ] ; then
	echo $USO
	exit
fi

function router {
	apt-get install vlan -y
	modprobe 8021q
	su -c 'echo "8021q" >> /etc/modules'

  stop network-manager

	cp ./router_3_interfaces /etc/network/interfaces

	ifdown eth0
	ifup eth0
	ifup eth1.31
	ifup eth1.32

	sysctl -w net.ipv4.ip_forward=1
	#O hacerlo permanente descomentando la linea en /etc/sysctl

	iptables -t nat -A POSTROUTING ! -d 192.168.0.0/16 -o eth0 -j MASQUERADE
	iptables-save
	apt-get install iptables-persistent -y

}


function server1 {
  stop network-manager
	cp ./server_31_interfaces /etc/network/interfaces
	ifdown eth0
	ifup eth0

  echo "nameserver 8.8.8.8" >> /etc/resolvconf/resolv.conf.d/head
}

function server2 {
  stop network-manager
	cp ./server_32_interfaces /etc/network/interfaces
	ifdown eth0
	ifup eth0

  echo "nameserver 8.8.8.8" >> /etc/resolvconf/resolv.conf.d/head
}


if [ $1 = "router" ] ; then
	router
elif [ $1 = "server1" ] ; then
	server1
elif [ $1 = "server2" ] ; then
	server2
else
	echo $USO
	exit
fi

ping -c 50 8.8.8.8
