#!/bin/bash

sudo apt-get install vlan
sudo modprobe 8021q
sudo su -c 'echo "8021q" >> /etc/modules'

read -p "Desactiva el gestor automático de la red. Activar red NO marcado. Pulsa enter para continuar."

echo "$Deity quiera que lo hayas hecho de verdad..."


sudo cp ./router_interfaces /etc/network/interfaces

sudo ifdown eth0
sudo ifup eth0
sudo ifup eth1.31
sudo ifup eth1.32



sudo sysctl -w net.ipv4.ip_forward=1
#O hacerlo permanente descomentando la linea en /etc/sysctl


sudo iptables -t nat -A POSTROUTING ! -d 192.168.0.0/16 -o eth0 -j MASQUERADE
sudo iptables-save
sudo apt-get install iptables-persistent

