#!/bin/bash

read -p "Desactiva el gestor automático de la red. Activar red NO marcado. Pulsa enter para continuar."

sudo cp ./server_32_interfaces /etc/network/interfaces

sudo ifdown eth0
sudo ifup eth0